#!/usr/bin/env python3
"""Canonical filesystem paths for the self-contained analysis project."""

from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]

SOURCE_DATA_DIR = PROJECT_ROOT / "1 Source Data"
RAW_EMIC_IWYMIC_DIR = SOURCE_DATA_DIR / "EMIC and IWYMIC"
RAW_APMO_DIR = SOURCE_DATA_DIR / "APMO"
RAW_IMO_DIR = SOURCE_DATA_DIR / "IMO"
NAME_REFERENCE_DIR = SOURCE_DATA_DIR / "Name References"
IMO_NAME_REFERENCE_PATH = NAME_REFERENCE_DIR / "IMO Name Reference.csv"

SCRIPTS_DIR = PROJECT_ROOT / "2 Processing Scripts"

PROCESSED_DATA_DIR = PROJECT_ROOT / "3 Processed Data"
EMIC_PROCESSED_DIR = PROCESSED_DATA_DIR / "EMIC"
IWYMIC_PROCESSED_DIR = PROCESSED_DATA_DIR / "IWYMIC"
COMBINED_PROCESSED_DIR = PROCESSED_DATA_DIR / "Combined"
HIGHER_PROCESSED_DIR = PROCESSED_DATA_DIR / "Higher Contests"

EMIC_AWARDED_PATH = EMIC_PROCESSED_DIR / "EMIC Awarded Appearances.csv"
EMIC_UNIQUE_PATH = EMIC_PROCESSED_DIR / "EMIC Unique Contestants.csv"
EMIC_MEDAL_SUMMARY_PATH = EMIC_PROCESSED_DIR / "EMIC Medal Summary.csv"
EMIC_MEDAL_BUCKETS_PATH = EMIC_PROCESSED_DIR / "EMIC Medal Buckets.csv"
EMIC_AUDIT_PATH = EMIC_PROCESSED_DIR / "EMIC Participant Audit.csv"
EMIC_CHANGELOG_PATH = EMIC_PROCESSED_DIR / "EMIC Changelog.txt"

IWYMIC_AWARDED_PATH = IWYMIC_PROCESSED_DIR / "IWYMIC Awarded Appearances.csv"
IWYMIC_UNIQUE_PATH = IWYMIC_PROCESSED_DIR / "IWYMIC Unique Contestants.csv"
IWYMIC_MEDAL_SUMMARY_PATH = IWYMIC_PROCESSED_DIR / "IWYMIC Medal Summary.csv"
IWYMIC_MEDAL_BUCKETS_PATH = IWYMIC_PROCESSED_DIR / "IWYMIC Medal Buckets.csv"
IWYMIC_AUDIT_PATH = IWYMIC_PROCESSED_DIR / "IWYMIC Participant Audit.csv"
IWYMIC_CHANGELOG_PATH = IWYMIC_PROCESSED_DIR / "IWYMIC Changelog.txt"

COMBINED_MASTER_PATH = (
    COMBINED_PROCESSED_DIR / "EMIC and IWYMIC Unique Contestants.csv"
)
DUPLICATE_REVIEW_PATH = COMBINED_PROCESSED_DIR / "Duplicate Name Review.csv"
COMBINED_CHANGELOG_PATH = COMBINED_PROCESSED_DIR / "Combined Changelog.txt"

APMO_MATCHED_PATH = HIGHER_PROCESSED_DIR / "APMO Matched Appearances.csv"
IMO_MATCHED_PATH = HIGHER_PROCESSED_DIR / "IMO Matched Appearances.csv"
HIGHER_AUDIT_PATH = HIGHER_PROCESSED_DIR / "APMO and IMO Audit.csv"
HIGHER_MATCH_REVIEW_PATH = HIGHER_PROCESSED_DIR / "APMO and IMO Match Review.csv"
HIGHER_CHANGELOG_PATH = HIGHER_PROCESSED_DIR / "APMO and IMO Changelog.txt"

COUNTRY_ANALYSIS_DIR = PROJECT_ROOT / "4 Country Analysis"
COUNTRY_PROGRESSION_SUMMARY_PATH = (
    COUNTRY_ANALYSIS_DIR / "Winner Progression by Country.csv"
)
DOCUMENTATION_DIR = PROJECT_ROOT / "5 Documentation"
STATISTICAL_ANALYSIS_DIR = PROJECT_ROOT / "6 Statistical Analysis"
MASTER_COPY_PATH = PROJECT_ROOT / "Master.csv"
PROJECT_CHANGELOG_PATH = PROJECT_ROOT / "Changelog.txt"
README_PATH = PROJECT_ROOT / "README.md"
